# Generated by Django 4.2.4 on 2023-08-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default='siema', max_length=150),
            preserve_default=False,
        ),
    ]
