# Generated by Django 4.2.4 on 2023-08-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0005_followsevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default='2023-08-25 12:34:56'),
            preserve_default=False,
        ),
    ]
