# Generated by Django 4.2.4 on 2023-08-28 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0007_savedevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='number_of_participants',
        ),
    ]
