# Generated by Django 4.2.4 on 2023-08-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0009_asd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_participants',
            field=models.CharField(max_length=100),
        ),
    ]
