# Generated by Django 4.2.4 on 2023-08-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0010_alter_event_max_participants'),
    ]

    operations = [
        migrations.DeleteModel(
            name='asd',
        ),
    ]
