# Generated by Django 4.2.4 on 2023-08-29 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0011_delete_asd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='member',
            new_name='user',
        ),
    ]
